version: '3.1'

services:
        shiftdb:
                image: postgres:shift
                container_name: shift_postgres
                env_file:
                        - .env
                environment:
                        - POSTGRES_DB=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                volumes:
                        - ~/.shift/psqlData:/var/lib/postgresql/data
                ports:
                        - 5432:5432 
