version: '3.1'

services:
        shift_brokerage_center:
                image: shift-base
                container_name: shift_broker
                command: BrokerageCenter -v
                network_mode: host
                env_file:
                        - .env
                ports:
                        - 5003:5003
        shift_matching_engine:
                image: shift-base
                container_name: shift_matching
                command: MatchingEngine
                network_mode: host
                env_file:
                        - .env
                ports:
                        - 5002:5002
        shift_datafeed_engine:
                image: shift-base
                container_name: shift_datafeed
                command: DatafeedEngine
                network_mode: host
                env_file:
                        - .env
                ports:
                        - 5001:5001
