/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef shift_service_CONSTANTS_H
#define shift_service_CONSTANTS_H

#include "shift_service_types.h"



class shift_serviceConstants {
 public:
  shift_serviceConstants();

};

extern const shift_serviceConstants g_shift_service_constants;



#endif
