/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

#include "shift_service_types.h"
