<?php
namespace client;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SHIFTService_getThisLeaderboard_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'startDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'endDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $startDate = "";
    /**
     * @var string
     */
    public $endDate = "";

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['startDate'])) {
                $this->startDate = $vals['startDate'];
            }
            if (isset($vals['endDate'])) {
                $this->endDate = $vals['endDate'];
            }
        }
    }

    public function getName()
    {
        return 'SHIFTService_getThisLeaderboard_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->startDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->endDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('SHIFTService_getThisLeaderboard_args');
        if ($this->startDate !== null) {
            $xfer += $output->writeFieldBegin('startDate', TType::STRING, 1);
            $xfer += $output->writeString($this->startDate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->endDate !== null) {
            $xfer += $output->writeFieldBegin('endDate', TType::STRING, 2);
            $xfer += $output->writeString($this->endDate);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
