<?php
namespace client;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class SHIFTService_registerUser_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'username',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'firstname',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'lastname',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'email',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'password',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $username = null;
    /**
     * @var string
     */
    public $firstname = null;
    /**
     * @var string
     */
    public $lastname = null;
    /**
     * @var string
     */
    public $email = null;
    /**
     * @var string
     */
    public $password = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['username'])) {
                $this->username = $vals['username'];
            }
            if (isset($vals['firstname'])) {
                $this->firstname = $vals['firstname'];
            }
            if (isset($vals['lastname'])) {
                $this->lastname = $vals['lastname'];
            }
            if (isset($vals['email'])) {
                $this->email = $vals['email'];
            }
            if (isset($vals['password'])) {
                $this->password = $vals['password'];
            }
        }
    }

    public function getName()
    {
        return 'SHIFTService_registerUser_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->username);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->firstname);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->lastname);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->email);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->password);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('SHIFTService_registerUser_args');
        if ($this->username !== null) {
            $xfer += $output->writeFieldBegin('username', TType::STRING, 1);
            $xfer += $output->writeString($this->username);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->firstname !== null) {
            $xfer += $output->writeFieldBegin('firstname', TType::STRING, 2);
            $xfer += $output->writeString($this->firstname);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->lastname !== null) {
            $xfer += $output->writeFieldBegin('lastname', TType::STRING, 3);
            $xfer += $output->writeString($this->lastname);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->email !== null) {
            $xfer += $output->writeFieldBegin('email', TType::STRING, 4);
            $xfer += $output->writeString($this->email);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->password !== null) {
            $xfer += $output->writeFieldBegin('password', TType::STRING, 5);
            $xfer += $output->writeString($this->password);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
